export enum ErrorMsg {
  /** http权限状态码 **/
  INVALID_IDENTITY_INFORMATION = '无效的用户信息',
  PERMISSION_DENIED = '权限不足',
  /** auth状态码 */
  TOKEN_INVALID = 'TOKEN INVALID',
  YOU_DO_NOT_OWN_THIS_RESOURCE = 'YOU DO NOT OWN THIS RESOURCE',
  VERIFICATION_CODE_ERROR = 'VERIFICATION ERROR',
  VERIFICATION_CODE_SEND_FAILED = 'VERIFICATION CODE SEND ERROR',
  /** 用户状态码 **/
  UNKNOWN_ERROR = 'UNKNOWN ERROR', //未知错误
  USER_ID_INVALID = 'USER ID INVALID', //用户id无效
  USER_NOT_EXIST = 'USER NOT EXIST', // 用户不存在
  USER_EXIST = 'USER EXIST',
  EMAIL_EXIST = 'EMAIL EXIST',
  AVATAR_UNSUPPORTED_FILE_TYPE = 'AVATAR UNSUPPORTED FILE TYPE',
  USERNAME_FORMAT_ERROR = '用户名只能是大小写字母、数字、下划线组成',
  USER_PROHIBITED = '用户被禁止访问，请联系管理员',
  /** 权限状态码 **/
  PERMISSION_EXIST = 'PERMISSION EXIST', //权限已存在
  PERMISSION_NOT_EXIST = 'PERMISSION_NOT EXIST', // 权限不存在
  /** 角色状态码 **/
  SUPER_ADMIN_READ_ONLY = 'SUPER ADMIN READ ONLY', // superAdmin只读，禁止任何处理
  ROLE_ACCESS_PROHIBITED = 'ROLE ACCESS PROHIBITED', //角色禁止访问
  ROLE_EXIST = 'ROLE EXIST', //角色已存在
  ROLE_NOT_EXIST = 'ROLE NOT EXIST', //角色不存在
  /** 动态状态码 */
  MOMENT_PARAMETER_VALUE_ERROR = 'MOMENT PARAMETER VALUE ERROR',
  MOMENT_UNSUPPORTED_IMAGE_FILE_TYPE = 'MOMENT UNSUPPORTED IMAGE FILE TYPE',
  MOMENT_UNSUPPORTED_VIDEO_FILE_TYPE = 'MOMENT UNSUPPORTED VIDEO FILE TYPE',
  MOMENT_NOT_EXIST = 'MOMENT NOT EXIST',
  REPLY_MOMENT_NOT_EXIST = 'REPLY MOMENT NOT EXIST',
  MOMENT_LABEL_EXIST = '动态标签已存在',
  /** 文章状态码 */
  ARTICLE_PARAMETER_VALUE_ERROR = 'ARTICLE PARAMETER VALUE ERROR',
  ARTICLE_NOT_EXIST = 'ARTICLE NOT EXIST',
  REPLY_ARTICLE_NOT_EXIST = 'REPLY ARTICLE NOT EXIST',
  ARTICLE_LABEL_EXIST = '文章标签已存在',
  /** 数据库错误 */
  DATABASE_HANDLE_ERROR = 'DATABASE_HANDLE_ERROR',
}
